<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-TKK594A" failures="1" tests="5" name="Personal Loan" time="0.107" errors="0" timestamp="2023-03-31T07:33:35 IST">
  <testcase classname="test.day1" name="Demo" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day2" name="ploan" time="0.002"/>
  <testcase classname="test.day4" name="LoginAPIhomeloan" time="0.002"/>
  <testcase classname="test.day4" name="MobileLoginhomeloan" time="0.003"/>
  <testcase classname="test.day4" name="Webloginhomeloan" time="0.002"/>
  <testcase classname="test.day1" name="secondTest" time="0.0">
    <ignored/>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Personal Loan -->
